---
AWSTemplateFormatVersion: 2010-09-09
Description: Lambda / Cloudformation custom resources
Parameters:
  Organization:
    Type: String
  Team:
    Type: String
  Env:
    Type: String
  CodeS3ObjectVersion:
    Type: String
  GitRevision:
    Type: String
Resources:

  # Lambda
  CertibotLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub '${Organization}-${Team}-${Env}-tools'
        S3Key: !Sub 'lambdas/${Organization}-${Team}-certibot.zip'
        S3ObjectVersion: !Ref CodeS3ObjectVersion
      Handler: lambda_handler.handler
      MemorySize: 128
      Role: !Sub '${CertibotRole.Arn}'
      Runtime: python3.6
      Timeout: 60
      Description: Kugawana GitHub inventory
      Environment:
        Variables:
          ENV: !Ref Env
          GIT_REVISION: !Ref GitRevision
    DependsOn:
      - CertibotRole
  CertibotPermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: CertibotLambda
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${CertibotApi}/*'
    DependsOn:
      - CertibotApi
  CertibotRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F3
            reason: Allow all resources action
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: lambda
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: >-
                  arn:aws:secretsmanager:eu-west-1:*:secret:prod/gtt/certibot*
              - Effect: Allow
                Action: logs:*
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action: dynamodb:*
                Resource: 'arn:aws:dynamodb:*:*:*'

  # Schedule for reporting
  CertibotAdminReportScheduledRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: Certibot admin report trigger
      ScheduleExpression: cron(0 8 ? * 2-6 *)
      State: ENABLED
      Targets:
        - Arn: !Sub '${CertibotLambda.Arn}'
          Id: TargetFunctionV1
          Input: "{\"report\":\"admin\"}"
    DependsOn:
      - CertibotLambda
  CertibotAdminReportPermissionForEventsToInvokeLambda:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName:
        Ref: CertibotLambda
      Action: 'lambda:InvokeFunction'
      Principal: events.amazonaws.com
      SourceArn: !Sub '${CertibotAdminReportScheduledRule.Arn}'

  CertibotUserReportScheduledRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: Certibot user report trigger
      ScheduleExpression: cron(0 10 ? * 2 *)
      State: ENABLED
      Targets:
        - Arn: !Sub '${CertibotLambda.Arn}'
          Id: TargetFunctionV1
          Input: "{\"report\":\"user\"}"
    DependsOn:
      - CertibotLambda
  CertibotUserReportPermissionForEventsToInvokeLambda:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName:
        Ref: CertibotLambda
      Action: 'lambda:InvokeFunction'
      Principal: events.amazonaws.com
      SourceArn: !Sub '${CertibotUserReportScheduledRule.Arn}'

  # ApiGateway Account
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !Sub '${ApiGatewayRole.Arn}'
  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ApiGatewayLogsPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: logs:*
                Resource: 'arn:aws:logs:*:*:*'

  # API Gateway
  CertibotApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: CertibotApi
      Description: API Gateway for Certibot
  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref APiGatewayDeployement
      MethodSettings:
        - DataTraceEnabled: true
          HttpMethod: '*'
          LoggingLevel: INFO
          ResourcePath: '/*'
      RestApiId: !Ref CertibotApi
      StageName: LATEST
  APiGatewayDeployement:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref CertibotApi
      StageName: DummyStage
    DependsOn:
      - VouchersMethod

  EventHandlerResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref CertibotApi
      ParentId: !Sub '${CertibotApi.RootResourceId}'
      PathPart: event-handler
  EventHandlerMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      ResourceId: !Sub '${EventHandlerResource}'
      RestApiId: !Ref CertibotApi
      Integration:
        Type: AWS
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CertibotLambda.Arn}/invocations'
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - ResponseModels:
            application/json: Empty
          StatusCode: 200
    DependsOn:
      - CertibotLambda

  SlashCommandResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref CertibotApi
      ParentId: !Sub '${CertibotApi.RootResourceId}'
      PathPart: slash-command
  SlashCommandMethod:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-eu-west-1.amazonaws.com/kugawana-gtt-prod-tools/templates/api-method-slackevent.template
      Parameters:
        RestApiId: !Ref 'CertibotApi'
        ResourceId: !Ref 'SlashCommandResource'
        IntegrationUriArn: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CertibotLambda.Arn}/invocations'
